# Generated by Django 3.0.8 on 2020-07-02 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=100)),
                ('Mobile_no', models.IntegerField()),
                ('Emailid', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('Product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Product_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_price', models.FloatField()),
                ('Product_image', models.ImageField(blank=True, default='image/abc.jpeg', upload_to='image/')),
                ('Product_model', models.CharField(max_length=150)),
                ('Product_ram', models.IntegerField()),
                ('Product_name_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Master')),
            ],
        ),
    ]
