# Generated by Django 3.0.8 on 2020-07-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='Product_image',
            field=models.ImageField(blank=True, default='image/default.jpeg', upload_to='image/'),
        ),
    ]
