# Generated by Django 3.0.8 on 2020-07-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200702_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='Product_model',
            field=models.CharField(max_length=100),
        ),
    ]
