# Generated by Django 3.0.8 on 2020-07-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200702_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='Product_price',
            field=models.IntegerField(),
        ),
    ]
