# Generated by Django 3.0.8 on 2020-07-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200702_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='Product_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='details',
            name='Product_ram',
            field=models.IntegerField(default=2),
        ),
    ]
