# Generated by Django 3.0.8 on 2020-07-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200702_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='Product_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='details',
            name='Product_ram',
            field=models.IntegerField(),
        ),
    ]
