# Generated by Django 3.0.8 on 2020-07-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200702_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='User_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Product Manager', 'Product Manager')], max_length=100, null=True),
        ),
    ]
