# Generated by Django 3.0.8 on 2020-07-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20200704_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='Product_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
