# Generated by Django 3.0.8 on 2020-07-15 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20200704_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_reviews', models.CharField(max_length=100)),
                ('User_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Admin')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_replies', models.CharField(max_length=100)),
                ('Reviews_replies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Reviews')),
            ],
        ),
        migrations.DeleteModel(
            name='Product_Manager',
        ),
    ]
