# Generated by Django 3.0.8 on 2020-07-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20200715_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='Product_detail',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
