# Generated by Django 3.0.8 on 2020-07-15 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20200715_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='R_created_at',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='R_updated_at',
        ),
        migrations.RemoveField(
            model_name='sub_reviews',
            name='S_R_created_at',
        ),
        migrations.RemoveField(
            model_name='sub_reviews',
            name='S_R_updated_at',
        ),
    ]
