# Generated by Django 3.0.8 on 2020-07-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20200715_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='R_created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='R_updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='sub_reviews',
            name='S_R_created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sub_reviews',
            name='S_R_updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
