# Generated by Django 3.0.8 on 2020-07-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20200715_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_reviews',
            name='User_replies',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
