# Generated by Django 3.0.8 on 2020-07-15 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_reviews_prod_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='Prod_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Details'),
        ),
    ]
