# Generated by Django 3.0.8 on 2020-07-19 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20200715_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_reviews',
            name='Rply_user_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Admin'),
        ),
    ]
