# Generated by Django 3.0.8 on 2020-07-20 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_auto_20200719_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sub_reviews',
            options={'verbose_name': 'Sub_Reviews (Reviewer, Replier)'},
        ),
    ]
